const FOOD_DB = [
  { name: "Pomme", kcal: 52 }, { name: "Banane", kcal: 89 }, { name: "Orange", kcal: 47 },
  { name: "Fraise", kcal: 33 }, { name: "Raisin", kcal: 69 }, { name: "Poire", kcal: 57 },
  { name: "Kiwi", kcal: 61 }, { name: "Mangue", kcal: 60 }, { name: "Ananas", kcal: 50 },
  { name: "Pêche", kcal: 39 }, { name: "Abricot", kcal: 48 }, { name: "Pastèque", kcal: 30 },
  { name: "Melon", kcal: 34 }, { name: "Cerise", kcal: 63 }, { name: "Avocat", kcal: 160 },
  { name: "Citron", kcal: 29 }, { name: "Framboise", kcal: 52 }, { name: "Myrtille", kcal: 57 },
  { name: "Tomate", kcal: 18 }, { name: "Carotte", kcal: 41 }, { name: "Concombre", kcal: 16 },
  { name: "Courgette", kcal: 17 }, { name: "Aubergine", kcal: 25 }, { name: "Poivron", kcal: 31 },
  { name: "Brocoli", kcal: 34 }, { name: "Chou-fleur", kcal: 25 }, { name: "Épinards", kcal: 23 },
  { name: "Salade verte", kcal: 15 }, { name: "Champignons", kcal: 22 }, { name: "Haricots verts", kcal: 31 },
  { name: "Petits pois", kcal: 81 }, { name: "Maïs doux", kcal: 86 }, { name: "Pomme de terre", kcal: 77 },
  { name: "Patate douce", kcal: 86 }, { name: "Oignon", kcal: 40 }, { name: "Ail", kcal: 149 },
  { name: "Pain blanc baguette", kcal: 274 }, { name: "Pain complet", kcal: 247 }, { name: "Pain de mie", kcal: 280 },
  { name: "Riz blanc cuit", kcal: 130 }, { name: "Riz complet cuit", kcal: 123 }, { name: "Pâtes cuites", kcal: 158 },
  { name: "Quinoa cuit", kcal: 120 }, { name: "Semoule cuite", kcal: 112 }, { name: "Boulgour cuit", kcal: 83 },
  { name: "Flocons d'avoine", kcal: 379 }, { name: "Muesli", kcal: 367 }, { name: "Corn flakes", kcal: 378 },
  { name: "Croissant", kcal: 406 }, { name: "Pain au chocolat", kcal: 414 }, { name: "Brioche", kcal: 359 },
  { name: "Lentilles cuites", kcal: 116 }, { name: "Pois chiches cuits", kcal: 164 }, { name: "Haricots rouges cuits", kcal: 127 },
  { name: "Poulet blanc cuit", kcal: 165 }, { name: "Poulet cuisse rôtie", kcal: 209 }, { name: "Dinde escalope", kcal: 135 },
  { name: "Boeuf steak haché 5%", kcal: 137 }, { name: "Boeuf steak haché 15%", kcal: 215 }, { name: "Porc filet", kcal: 145 },
  { name: "Jambon blanc", kcal: 110 }, { name: "Jambon cru", kcal: 240 }, { name: "Saucisson sec", kcal: 470 },
  { name: "Lardons", kcal: 290 }, { name: "Veau escalope", kcal: 130 }, { name: "Agneau", kcal: 235 },
  { name: "Saumon", kcal: 208 }, { name: "Thon au naturel", kcal: 116 }, { name: "Thon a l'huile", kcal: 198 },
  { name: "Cabillaud", kcal: 82 }, { name: "Sardines", kcal: 220 }, { name: "Maquereau", kcal: 205 },
  { name: "Crevettes", kcal: 99 }, { name: "Truite", kcal: 148 }, { name: "Sole", kcal: 86 },
  { name: "Oeuf entier", kcal: 143 }, { name: "Blanc d'oeuf", kcal: 52 },
  { name: "Lait demi-ecreme", kcal: 46 }, { name: "Lait entier", kcal: 64 }, { name: "Lait ecreme", kcal: 33 },
  { name: "Yaourt nature", kcal: 60 }, { name: "Yaourt grec", kcal: 97 }, { name: "Yaourt aux fruits", kcal: 95 },
  { name: "Fromage blanc 0%", kcal: 47 }, { name: "Skyr", kcal: 63 }, { name: "Creme fraiche", kcal: 290 },
  { name: "Beurre", kcal: 750 }, { name: "Camembert", kcal: 299 }, { name: "Emmental", kcal: 380 },
  { name: "Comte", kcal: 410 }, { name: "Mozzarella", kcal: 254 }, { name: "Parmesan", kcal: 392 },
  { name: "Roquefort", kcal: 369 }, { name: "Chevre frais", kcal: 254 }, { name: "Feta", kcal: 264 },
  { name: "Cheddar", kcal: 403 }, { name: "Brie", kcal: 334 },
  { name: "Huile d'olive", kcal: 884 }, { name: "Mayonnaise", kcal: 680 }, { name: "Vinaigrette", kcal: 450 },
  { name: "Chocolat noir", kcal: 540 }, { name: "Chocolat au lait", kcal: 535 }, { name: "Chocolat blanc", kcal: 558 },
  { name: "Nutella", kcal: 539 }, { name: "M&M's", kcal: 492 }, { name: "Kinder Bueno", kcal: 571 },
  { name: "Oreo", kcal: 480 }, { name: "Pringles", kcal: 536 }, { name: "Chips", kcal: 536 },
  { name: "Cacahuetes", kcal: 567 }, { name: "Amandes", kcal: 579 }, { name: "Noix", kcal: 654 },
  { name: "Noisettes", kcal: 628 }, { name: "Pistaches", kcal: 560 }, { name: "Madeleine", kcal: 430 },
  { name: "Biscuit Petit Beurre", kcal: 451 }, { name: "Speculoos", kcal: 480 },
  { name: "Tarte aux pommes", kcal: 245 }, { name: "Glace vanille", kcal: 207 },
  { name: "Confiture", kcal: 260 }, { name: "Miel", kcal: 304 }, { name: "Sucre", kcal: 400 },
  { name: "Coca-Cola", kcal: 42 }, { name: "Coca Zero", kcal: 0 }, { name: "Orangina", kcal: 44 },
  { name: "Jus d'orange", kcal: 45 }, { name: "Jus de pomme", kcal: 46 }, { name: "Cafe noir", kcal: 2 },
  { name: "The nature", kcal: 1 }, { name: "Biere blonde", kcal: 43 }, { name: "Vin rouge", kcal: 85 },
  { name: "Vin blanc", kcal: 82 }, { name: "Champagne", kcal: 76 }, { name: "Whisky", kcal: 250 },
  { name: "Red Bull", kcal: 45 }, { name: "Smoothie fruits rouges", kcal: 60 },
  { name: "Pizza margherita", kcal: 240 }, { name: "Pizza quatre fromages", kcal: 280 },
  { name: "Quiche lorraine", kcal: 285 }, { name: "Lasagnes bolognaise", kcal: 145 },
  { name: "Couscous poulet", kcal: 145 }, { name: "Sushi saumon", kcal: 175 },
  { name: "Burger", kcal: 260 }, { name: "Big Mac", kcal: 257 }, { name: "Frites", kcal: 165 },
  { name: "Kebab", kcal: 215 }, { name: "Salade Cesar", kcal: 165 }, { name: "Soupe legumes", kcal: 35 },
  { name: "Houmous", kcal: 220 }, { name: "Guacamole", kcal: 165 },
];
